#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' " Desinstalador do monitor de trafego  " ; tput sgr0
tput setaf 3 ; tput bold ; echo "  Debian, Ubuntu e CentOS (32|64 bits), Este script irá:  " ; echo ""
echo "● Desinstalar o monitor de trafego e todos seus componentes"
echo "● Confirm Y para todas as perguntas..." ; tput sgr0
tput setaf 3 ; tput bold ; read -n 1 -s -p "Ctrl+c para cancelar ou Aperte qualquer tecla para continuar..." ; tput sgr0
apt-get purge --auto-remove ntop
